// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQwLqow23lQoeNHqnoZvHMvuk8_mhoIjE',
    appId: '1:573562833379:web:f89fc12ebaa57d64a838d6',
    messagingSenderId: '573562833379',
    projectId: 'promptgpt-4092e',
    authDomain: 'promptgpt-4092e.firebaseapp.com',
    storageBucket: 'promptgpt-4092e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYeZJrehQ-_lasrORPqU4ux1_t4XQ-7xQ',
    appId: '1:573562833379:android:9c7541fdf83bf0cfa838d6',
    messagingSenderId: '573562833379',
    projectId: 'promptgpt-4092e',
    storageBucket: 'promptgpt-4092e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZUgwpL0J0BZKLQNdonjq1P2r6D1Orx4',
    appId: '1:573562833379:ios:c31adeafd064fc85a838d6',
    messagingSenderId: '573562833379',
    projectId: 'promptgpt-4092e',
    storageBucket: 'promptgpt-4092e.firebasestorage.app',
    iosBundleId: 'com.example.promptgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuZUgwpL0J0BZKLQNdonjq1P2r6D1Orx4',
    appId: '1:573562833379:ios:c31adeafd064fc85a838d6',
    messagingSenderId: '573562833379',
    projectId: 'promptgpt-4092e',
    storageBucket: 'promptgpt-4092e.firebasestorage.app',
    iosBundleId: 'com.example.promptgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQwLqow23lQoeNHqnoZvHMvuk8_mhoIjE',
    appId: '1:573562833379:web:a6d444b3f96e4bf6a838d6',
    messagingSenderId: '573562833379',
    projectId: 'promptgpt-4092e',
    authDomain: 'promptgpt-4092e.firebaseapp.com',
    storageBucket: 'promptgpt-4092e.firebasestorage.app',
  );
}
