// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY3OojprNgzVZsT-OohnmFZ4SxeVfAFFw',
    appId: '1:489591589895:web:e0596b394b4dfff6ef6ea2',
    messagingSenderId: '489591589895',
    projectId: 'promptgpt-26259',
    authDomain: 'promptgpt-26259.firebaseapp.com',
    storageBucket: 'promptgpt-26259.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPysl6szxJC32DZCzrqiEwUnDqdJ7HUDM',
    appId: '1:489591589895:android:b91f27f4cc511a6def6ea2',
    messagingSenderId: '489591589895',
    projectId: 'promptgpt-26259',
    storageBucket: 'promptgpt-26259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5C0RGSeJAIVoo-q1VWB9l3pZt3VadJME',
    appId: '1:489591589895:ios:7a4fdc67100da5f3ef6ea2',
    messagingSenderId: '489591589895',
    projectId: 'promptgpt-26259',
    storageBucket: 'promptgpt-26259.firebasestorage.app',
    iosBundleId: 'com.example.promptgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5C0RGSeJAIVoo-q1VWB9l3pZt3VadJME',
    appId: '1:489591589895:ios:7a4fdc67100da5f3ef6ea2',
    messagingSenderId: '489591589895',
    projectId: 'promptgpt-26259',
    storageBucket: 'promptgpt-26259.firebasestorage.app',
    iosBundleId: 'com.example.promptgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY3OojprNgzVZsT-OohnmFZ4SxeVfAFFw',
    appId: '1:489591589895:web:d7fe75773bd8236fef6ea2',
    messagingSenderId: '489591589895',
    projectId: 'promptgpt-26259',
    authDomain: 'promptgpt-26259.firebaseapp.com',
    storageBucket: 'promptgpt-26259.firebasestorage.app',
  );

}