name: promptgpt
description: "A new Flutter project."

publish_to: 'none'  # Do not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"  # Specify SDK version range for compatibility

dependencies:
  flutter_launcher_icons: ^0.14.1
  http: ^0.13.4
  cloud_firestore: ^5.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.1.2
  google_fonts: ^4.0.3
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/applogo.png" # This is your main app icon
  adaptive_icon_foreground: "lib/images/rpgptlogo.png" # Circular foreground image
  adaptive_icon_background: "#000000"
